# Site Build Settings

# jekyll-paginate configuration
paginate: 5

# Build settings
markdown: kramdown
highlighter: rouge
permalink: none
plugins: [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag, jekyll-analytics]

sass:
  sass_dir: assets/css
  style: :nested

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title: "Home Decoration"
description: "a home decoration ideas blog"
author: "Blend"

jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: UA-151653945-2      # Required - replace with your tracking id
    anonymizeIp: false      # Optional - Default: false - set to true for anonymized tracking
    
# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml